version: '2.2'
services:
  portainer:
    image: portainer/portainer
    ports:
     - 9000:9000
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    init: true

  roscore:
    image: ros:indigo-ros-core
    command: roscore
    network_mode: "host"
    restart: always
    init: true
