#! /usr/bin/env python
from __future__ import print_function

import os
import signal
import sys
import threading
import time

import actionlib
import actionlib_msgs.msg
import cogrob_navigation_msgs.msg
import std_msgs.msg
import rospy

class MoveToNavPointTopicProxy(object):
  def __init__(self):
    self._client = actionlib.SimpleActionClient(
        "/cogrob/move_to_nav_point",
        cogrob_navigation_msgs.msg.MoveToNavPointAction)
    self._client.wait_for_server()
    rospy.Subscriber("/cogrob/move_to_nav_point",
                     std_msgs.msg.String, self.TopicCallback)


  def TopicCallback(self, msg):
    goal = cogrob_navigation_msgs.msg.MoveToNavPointGoal()
    goal.target_nav_point = msg.data
    self._client.send_goal(goal)

if __name__ == '__main__':
  rospy.init_node("move_to_nav_point_topic_proxy")
  topic_proxy = MoveToNavPointTopicProxy()
  rospy.spin()
