# Name of configuration (representing a group of topics to record), this is also
# used as identifier -- at the same time, only one instance of a config could be
# actively recording.
string config_name

# Restarts a new bag file if already recording
bool restart

  ---

bool success
string error_info
