package(
  default_visibility = ["//cogrob/dialogue:__subpackages__"],
)

py_library(
  name = "all_quiz",
  srcs = [
    "all_quiz.py",
  ],
)

py_test(
  name = "all_quiz_test",
  srcs = [
    "all_quiz_test.py",
  ],
  deps = [
    ":all_quiz",
  ]
)

# TODO(shengye): Adds a program that pronounces all the quiz.
