package(
  default_visibility = ["//cogrob/dialogue:__subpackages__"],
)

py_library(
  name = "tour_info",
  srcs = [
    "tour_info.py",
  ],
)

py_test(
  name = "tour_info_test",
  srcs = [
    "tour_info_test.py",
  ],
  deps = [
    ":tour_info",
  ]
)

# TODO(shengye): Adds a program that pronounces all the introductions.
